# -*- coding: utf-8 -*-
"""2.OLSRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OMKbWEozfxSOBX9hxNP3I1pCZo9kNkQ

# OLS Regression

###**Run overall OLS regression**
"""

import statsmodels.api as sm

# Define the independent variable (hospitality_index) and add a constant for the full dataset
X_full = sm.add_constant(df[['hospitality_index']])

# Define the dependent variable (GDP) for the full dataset
y_full = df['GDP']

# Run the OLS regression model for the full dataset
model_full = sm.OLS(y_full, X_full).fit()

# Print the summary of the regression results
print(model_full.summary())

"""###**OLS for past five years**"""

import statsmodels.api as sm
import pandas as pd

# Determine the start date for the last five years
five_years_ago = df.index.max() - pd.DateOffset(years=5)

# Filter the DataFrame for the last five years
df_last_5_years = df[df.index >= five_years_ago]

# Define the independent variable (hospitality_index) and add a constant
X_5_years = sm.add_constant(df_last_5_years[['hospitality_index']])

# Define the dependent variable (GDP)
y_5_years = df_last_5_years['GDP']

# Run the OLS regression model for the last five years
model_5_years = sm.OLS(y_5_years, X_5_years).fit()

# Print the summary of the regression results
print(model_5_years.summary())

"""###**Save regression tables and interpretations to files**"""

import os

results_folder = os.path.join(project_root, 'results')
os.makedirs(results_folder, exist_ok=True)

# Prepare the interpretation for the full dataset model
interpretation_full = f"\n\nOLS INTERPRETATION (Full Dataset):\n"
interpretation_full += f"R-squared: {model_full.rsquared:.3f}\n"
interpretation_full += f"Coefficient on hospitality_index: {model_full.params['hospitality_index']:.2f}\n"
if model_full.pvalues['hospitality_index'] < 0.05:
    interpretation_full += "→ Statistically significant.\n"
else:
    interpretation_full += "→ Not statistically significant.\n"

# Save the summary of the full dataset regression model and its interpretation
summary_full_path = os.path.join(results_folder, 'ols_summary_full_dataset.txt')
with open(summary_full_path, 'w') as f:
    f.write(model_full.summary().as_text())
    f.write(interpretation_full)
print(f"Full dataset OLS regression summary and interpretation saved to: {summary_full_path}")

# Prepare the interpretation for the 5-year model
interpretation_5_years = f"\n\nOLS INTERPRETATION (Last 5 Years):\n"
interpretation_5_years += f"R-squared: {model_5_years.rsquared:.3f}\n"
interpretation_5_years += f"Coefficient on hospitality_index: {model_5_years.params['hospitality_index']:.2f}\n"
if model_5_years.pvalues['hospitality_index'] < 0.05:
    interpretation_5_years += "→ Statistically significant.\n"
else:
    interpretation_5_years += "→ Not statistically significant.\n"

# Save the summary of the 5-year regression model and its interpretation
summary_5_years_path = os.path.join(results_folder, 'ols_summary_5_years.txt')
with open(summary_5_years_path, 'w') as f:
    f.write(model_5_years.summary().as_text())
    f.write(interpretation_5_years)
print(f"5-year OLS regression summary and interpretation saved to: {summary_5_years_path}")