# -*- coding: utf-8 -*-
"""3.LASSORegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7pRwcgNCpRqaAjmET1Vo2UfzgupzovQ

# LASSO regression

### LASSO Regression (Full Dataset) - Using Hospitality Index and Lagged GDP
"""

from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import os

# Ensure df has the latest lagged and growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change
df_model_hosp_gdp = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

# 1. Prepare data
X_hosp_gdp = df_model_hosp_gdp[['GDP_lag1', 'hospitality_index']]
y_hosp_gdp = df_model_hosp_gdp['GDP_growth']

# Scale predictors (LASSO requires scaling)
scaler_hosp_gdp = StandardScaler()
X_scaled_hosp_gdp = scaler_hosp_gdp.fit_transform(X_hosp_gdp)

# 2. Run LASSO with CV
lasso_hosp_gdp = LassoCV(cv=5, random_state=42)
lasso_hosp_gdp.fit(X_scaled_hosp_gdp, y_hosp_gdp)

# 3. Print model information
print("Best alpha (λ) for Lasso (Hospitality Index & GDP_lag1, Full Dataset):", lasso_hosp_gdp.alpha_)
print("\nCoefficients (Hospitality Index & GDP_lag1, Full Dataset):")

coef_table_hosp_gdp = pd.DataFrame({
    'feature': X_hosp_gdp.columns,
    'coefficient': lasso_hosp_gdp.coef_,
})

print(coef_table_hosp_gdp)

# Identify which features LASSO kept
selected_features_hosp_gdp = coef_table_hosp_gdp[coef_table_hosp_gdp['coefficient'] != 0]['feature'].tolist()
zeroed_features_hosp_gdp = coef_table_hosp_gdp[coef_table_hosp_gdp['coefficient'] == 0]['feature'].tolist()

print("\nSelected features (non-zero):", selected_features_hosp_gdp)
print("Zeroed-out features:", zeroed_features_hosp_gdp)


# 4. Save results
results_folder = os.path.join(project_root, 'results')
coef_table_hosp_gdp.to_csv(os.path.join(results_folder, "lasso_coefficients_hosp_gdp_full_dataset.csv"))
print("\nSaved Lasso coefficient table (Hospitality Index & GDP_lag1, Full Dataset) to /results folder.")

"""### LASSO Regression (Last 5 Years) - Using Hospitality Index and Lagged GDP"""

from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import os

# Ensure df has the latest lagged and growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change
df_model_full_lasso_5yr_hosp_gdp = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

# Filter df_model for only the last five years
five_years_ago_lasso_5yr_hosp_gdp = df_model_full_lasso_5yr_hosp_gdp.index.max() - pd.DateOffset(years=5)
df_model_5_years_lasso_5yr_hosp_gdp = df_model_full_lasso_5yr_hosp_gdp[df_model_full_lasso_5yr_hosp_gdp.index >= five_years_ago_lasso_5yr_hosp_gdp]


# 1. Prepare data
X_lasso_5_years_hosp_gdp = df_model_5_years_lasso_5yr_hosp_gdp[['GDP_lag1', 'hospitality_index']]
y_lasso_5_years_hosp_gdp = df_model_5_years_lasso_5yr_hosp_gdp['GDP_growth']

# Scale predictors (LASSO requires scaling)
scaler_lasso_5_years_hosp_gdp = StandardScaler()
X_scaled_lasso_5_years_hosp_gdp = scaler_lasso_5_years_hosp_gdp.fit_transform(X_lasso_5_years_hosp_gdp)

# 2. Run LASSO with CV
lasso_5_years_hosp_gdp = LassoCV(cv=5, random_state=42)
lasso_5_years_hosp_gdp.fit(X_scaled_lasso_5_years_hosp_gdp, y_lasso_5_years_hosp_gdp)

# 3. Print model information
print("Best alpha (λ) for 5-year Lasso (Hospitality Index & GDP_lag1):", lasso_5_years_hosp_gdp.alpha_)
print("\nCoefficients for 5-year Lasso (Hospitality Index & GDP_lag1):")

coef_table_5_years_hosp_gdp = pd.DataFrame({
    'feature': X_lasso_5_years_hosp_gdp.columns,
    'coefficient': lasso_5_years_hosp_gdp.coef_,
})

print(coef_table_5_years_hosp_gdp)

# Identify which features LASSO kept
selected_features_5_years_hosp_gdp = coef_table_5_years_hosp_gdp[coef_table_5_years_hosp_gdp['coefficient'] != 0]['feature'].tolist()
zeroed_features_5_years_hosp_gdp = coef_table_5_years_hosp_gdp[coef_table_5_years_hosp_gdp['coefficient'] == 0]['feature'].tolist()

print("\nSelected features (non-zero) for 5-year Lasso:", selected_features_5_years_hosp_gdp)
print("Zeroed-out features for 5-year Lasso:", zeroed_features_5_years_hosp_gdp)


# 4. Save results
results_folder = os.path.join(project_root, 'results')
coef_table_5_years_hosp_gdp.to_csv(os.path.join(results_folder, "lasso_coefficients_hosp_gdp_5_years.csv"))
print("\nSaved 5-year Lasso coefficient table (Hospitality Index & GDP_lag1) to /results folder.")