# -*- coding: utf-8 -*-
"""4.RFNowcastingmodelandvalidation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qd1GNeVKUP3nzX-pAC8oyc5P2_onZYGY

# Random Forest Regression

### **Random Forest regression for whole data set**
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd  # Import pandas for DataFrame creation

# Create lagged GDP and GDP growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change
df_model = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

X = df_model[['GDP_lag1', 'hospitality_index']]
y = df_model['GDP_growth']

tscv = TimeSeriesSplit(n_splits=5)

all_preds = []
all_actuals = []
all_dates = []  # To store dates for each prediction

for train_idx, test_idx in tscv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    rf = RandomForestRegressor(n_estimators=500, random_state=42)
    rf.fit(X_train, y_train)

    pred = rf.predict(X_test)
    all_preds.extend(pred)
    all_actuals.extend(y_test.tolist())  # Convert Series to list
    all_dates.extend(y_test.index.tolist())  # Store dates

# Create a DataFrame for easier plotting and filtering
nowcast_results_df = pd.DataFrame({
    'date': all_dates,
    'actual': all_actuals,
    'predicted': all_preds,
}).set_index('date').sort_index()

rmse = np.sqrt(mean_squared_error(all_actuals, all_preds))
print("RF RMSE:", rmse)

"""###**Create graph for Full time period of nowcasting**"""

import matplotlib.pyplot as plt
import pandas as pd

plt.figure(figsize=(12, 6))
plt.plot(nowcast_results_df.index, nowcast_results_df['actual'], label="Actual GDP Growth")
plt.plot(nowcast_results_df.index, nowcast_results_df['predicted'], label="Predicted GDP Growth")
plt.legend()
plt.title("Nowcast vs Actual GDP Growth (Full Dataset)")
plt.xlabel("Date")
plt.ylabel("GDP Growth")
plt.grid(True)
plt.show()

"""### **Random Forest Regression - Trained on Last 5 Years of Data**"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd

# Ensure df has the latest lagged and growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change for the full dataset
df_model_full = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

# Filter df_model for only the last five years for training
five_years_ago_train = df_model_full.index.max() - pd.DateOffset(years=5)
df_model_5_years_train = df_model_full[df_model_full.index >= five_years_ago_train]

X_5_years_train = df_model_5_years_train[['GDP_lag1', 'hospitality_index']]
y_5_years_train = df_model_5_years_train['GDP_growth']

tscv_5_years = TimeSeriesSplit(n_splits=3)  # Reduced splits for potentially smaller dataset

all_preds_5_years = []
all_actuals_5_years = []
all_dates_5_years = []

for train_idx, test_idx in tscv_5_years.split(X_5_years_train):
    X_train_5_years, X_test_5_years = X_5_years_train.iloc[train_idx], X_5_years_train.iloc[test_idx]
    y_train_5_years, y_test_5_years = y_5_years_train.iloc[train_idx], y_5_years_train.iloc[test_idx]

    rf_5_years = RandomForestRegressor(n_estimators=500, random_state=42)
    rf_5_years.fit(X_train_5_years, y_train_5_years)

    pred_5_years = rf_5_years.predict(X_test_5_years)
    all_preds_5_years.extend(pred_5_years)
    all_actuals_5_years.extend(y_test_5_years.tolist())
    all_dates_5_years.extend(y_test_5_years.index.tolist())

# Create a DataFrame for results specific to this 5-year training
nowcast_results_df_5_years_trained = pd.DataFrame({
    'date': all_dates_5_years,
    'actual': all_actuals_5_years,
    'predicted': all_preds_5_years,
}).set_index('date').sort_index()

rmse_5_years_trained = np.sqrt(mean_squared_error(all_actuals_5_years, all_preds_5_years))
print("RF RMSE (Model Trained Only on Last 5 Years Data):", rmse_5_years_trained)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(nowcast_results_df_5_years_trained.index, nowcast_results_df_5_years_trained['actual'], label="Actual GDP Growth")
plt.plot(nowcast_results_df_5_years_trained.index, nowcast_results_df_5_years_trained['predicted'], label="Predicted GDP Growth")
plt.legend()
plt.title("Nowcast vs Actual GDP Growth (Model Trained on Last 5 Years)")
plt.xlabel("Date")
plt.ylabel("GDP Growth")
plt.grid(True)
plt.show()

"""###**Save RFR models**"""

import os

results_folder = os.path.join(project_root, 'results')
os.makedirs(results_folder, exist_ok=True)

# Save the full dataset nowcasting results
nowcast_full_path = os.path.join(results_folder, 'nowcast_results_full_dataset.csv')
nowcast_results_df.to_csv(nowcast_full_path)
print(f"Full dataset nowcasting results saved to: {nowcast_full_path}")

# Save the nowcasting results from the model trained on the last five years
nowcast_5yr_trained_path = os.path.join(results_folder, 'nowcast_results_5_years_trained.csv')
nowcast_results_df_5_years_trained.to_csv(nowcast_5yr_trained_path)
print(f"Nowcasting results (model trained on last 5 years) saved to: {nowcast_5yr_trained_path}")

"""Model Validation"""

import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

# --- 1. Prepare X and Y for the full dataset model (as in jXDIeJxOyn2Z) ---
# Ensure df has the latest lagged and growth features (if not already done)
# This is for robustness, as these steps are typically run before.
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()
df_model_full_for_validation = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

X_full_for_validation = df_model_full_for_validation[['GDP_lag1', 'hospitality_index']]
y_full_for_validation = df_model_full_for_validation['GDP_growth']

# --- 2. Calculate and print MAE for the full dataset nowcasting model ---
# nowcast_results_df is available from jXDIeJxOyn2Z
if 'nowcast_results_df' in locals():
    mae_full = mean_absolute_error(nowcast_results_df['actual'], nowcast_results_df['predicted'])
    print(f"Full Dataset Nowcasting - Mean Absolute Error (MAE): {mae_full:.4f}")
else:
    print("nowcast_results_df not found. Please ensure the full dataset RF cell (jXDIeJxOyn2Z) has been run.")


# --- 3. Plot Residuals for the full dataset nowcasting model ---
if 'nowcast_results_df' in locals():
    nowcast_results_df['residuals'] = nowcast_results_df['actual'] - nowcast_results_df['predicted']

    # Ensure residuals for the 5-year trained model are also calculated before concatenation
    if 'nowcast_results_df_5_years_trained' in locals():
        nowcast_results_df_5_years_trained['residuals'] = nowcast_results_df_5_years_trained['actual'] - nowcast_results_df_5_years_trained['predicted']

    # Determine global y-limits for consistent scaling
    all_residuals = pd.concat([nowcast_results_df['residuals']])
    if 'nowcast_results_df_5_years_trained' in locals():
        all_residuals = pd.concat([all_residuals, nowcast_results_df_5_years_trained['residuals']])

    y_min_global = all_residuals.min() * 1.1 # Add a little padding
    y_max_global = all_residuals.max() * 1.1 # Add a little padding

    plt.figure(figsize=(12, 6))
    plt.plot(nowcast_results_df.index, nowcast_results_df['residuals'], label="Residuals")
    plt.axhline(0, color='red', linestyle='--', linewidth=0.8)
    plt.legend()
    plt.title("Residuals of Nowcast vs Actual GDP Growth (Full Dataset)")
    plt.xlabel("Date")
    plt.ylabel("Residuals (Actual - Predicted)")
    plt.ylim(y_min_global, y_max_global) # Apply global limits
    plt.grid(True)
    plt.show()
else:
    print("Cannot plot residuals for full dataset: nowcast_results_df not found.")


# --- 4 & 5. Train a final RF model on the full dataset for Feature Importance ---
# This rf_final model is trained on the entire relevant dataset (X_full_for_validation, y_full_for_validation)
# to get a single set of feature importances.
rf_final = RandomForestRegressor(n_estimators=500, random_state=42)
rf_final.fit(X_full_for_validation, y_full_for_validation)

print("\nFeature Importances for Full Dataset Random Forest Model:")
feature_importances = pd.Series(rf_final.feature_importances_, index=X_full_for_validation.columns)
print(feature_importances.sort_values(ascending=False))

# --- 6. Calculate MAE and plot residuals for the 5-year trained model ---
# nowcast_results_df_5_years_trained is available from fd881ec4
if 'nowcast_results_df_5_years_trained' in locals():
    mae_5_years_trained = mean_absolute_error(nowcast_results_df_5_years_trained['actual'], nowcast_results_df_5_years_trained['predicted'])
    print(f"\n5-Year Trained Nowcasting - Mean Absolute Error (MAE): {mae_5_years_trained:.4f}")

    # The 'residuals' column for nowcast_results_df_5_years_trained is now created earlier
    plt.figure(figsize=(12, 6))
    plt.plot(nowcast_results_df_5_years_trained.index, nowcast_results_df_5_years_trained['residuals'], label="Residuals")
    plt.axhline(0, color='red', linestyle='--', linewidth=0.8)
    plt.legend()
    plt.title("Residuals of Nowcast vs Actual GDP Growth (Model Trained on Last 5 Years)")
    plt.xlabel("Date")
    plt.ylabel("Residuals (Actual - Predicted)")
    plt.ylim(y_min_global, y_max_global) # Apply global limits
    plt.grid(True)
    plt.show()
else:
    print("\nnowcast_results_df_5_years_trained not found. Please ensure the 5-year trained RF cell (fd881ec4) has been run.")

# --- 7. Train a final RF model on the 5-year dataset for Feature Importance ---
# Ensure df_model_5_years_train from fd881ec4 is available.
# Re-create X_5_years_train and y_5_years_train for clarity and robustness.
# Using the same logic as in fd881ec4 to define the 5-year training data.
five_years_ago_train = df_model_full_for_validation.index.max() - pd.DateOffset(years=5)
df_model_5_years_train_for_fi = df_model_full_for_validation[df_model_full_for_validation.index >= five_years_ago_train]

X_5_years_train_for_fi = df_model_5_years_train_for_fi[['GDP_lag1', 'hospitality_index']]
y_5_years_train_for_fi = df_model_5_years_train_for_fi['GDP_growth']

rf_5_years_fi = RandomForestRegressor(n_estimators=500, random_state=42)
rf_5_years_fi.fit(X_5_years_train_for_fi, y_5_years_train_for_fi)

print("\nFeature Importances for 5-Year Random Forest Model:")
feature_importances_5_years = pd.Series(rf_5_years_fi.feature_importances_, index=X_5_years_train_for_fi.columns)
print(feature_importances_5_years.sort_values(ascending=False))

import os
import matplotlib.pyplot as plt
import pandas as pd

# Define the path to the models folder
models_folder = os.path.join(project_root, 'models')
os.makedirs(models_folder, exist_ok=True)

# --- Save Residual Plots ---

# 1. Residual Plot for Full Dataset
if 'nowcast_results_df' in locals() and not nowcast_results_df.empty:
    plt.figure(figsize=(12, 6))
    plt.plot(nowcast_results_df.index, nowcast_results_df['residuals'], label="Residuals")
    plt.axhline(0, color='red', linestyle='--', linewidth=0.8)
    plt.legend()
    plt.title("Residuals of Nowcast vs Actual GDP Growth (Full Dataset)")
    plt.xlabel("Date")
    plt.ylabel("Residuals (Actual - Predicted)")
    # Use global limits if available, otherwise determine for this plot
    if 'y_min_global' in locals() and 'y_max_global' in locals():
        plt.ylim(y_min_global, y_max_global)
    plt.grid(True)
    full_residuals_path = os.path.join(models_folder, 'full_dataset_residuals.png')
    plt.savefig(full_residuals_path)
    plt.close() # Close plot to free up memory
    print(f"Full dataset residuals plot saved to: {full_residuals_path}")

# 2. Residual Plot for 5-Year Trained Model
if 'nowcast_results_df_5_years_trained' in locals() and not nowcast_results_df_5_years_trained.empty:
    plt.figure(figsize=(12, 6))
    plt.plot(nowcast_results_df_5_years_trained.index, nowcast_results_df_5_years_trained['residuals'], label="Residuals")
    plt.axhline(0, color='red', linestyle='--', linewidth=0.8)
    plt.legend()
    plt.title("Residuals of Nowcast vs Actual GDP Growth (Model Trained on Last 5 Years)")
    plt.xlabel("Date")
    plt.ylabel("Residuals (Actual - Predicted)")
    # Use global limits if available, otherwise determine for this plot
    if 'y_min_global' in locals() and 'y_max_global' in locals():
        plt.ylim(y_min_global, y_max_global)
    plt.grid(True)
    five_year_residuals_path = os.path.join(models_folder, 'five_year_trained_residuals.png')
    plt.savefig(five_year_residuals_path)
    plt.close() # Close plot
    print(f"5-year trained residuals plot saved to: {five_year_residuals_path}")

# --- Save Feature Importances ---
if 'feature_importances' in locals():
    feature_importances_path_full = os.path.join(models_folder, 'feature_importances_full_dataset.txt')
    with open(feature_importances_path_full, 'w') as f:
        f.write("Feature Importances for Full Dataset Random Forest Model:\n")
        f.write(feature_importances.sort_values(ascending=False).to_string())
    print(f"Feature importances for full dataset saved to: {feature_importances_path_full}")

if 'feature_importances_5_years' in locals():
    feature_importances_path_5_years = os.path.join(models_folder, 'feature_importances_5_years.txt')
    with open(feature_importances_path_5_years, 'w') as f:
        f.write("Feature Importances for 5-Year Random Forest Model:\n")
        f.write(feature_importances_5_years.sort_values(ascending=False).to_string())
    print(f"Feature importances for 5-year model saved to: {feature_importances_path_5_years}")

# --- Save MAE Values ---
mae_values_path = os.path.join(models_folder, 'mae_values.txt')
with open(mae_values_path, 'w') as f:
    if 'mae_full' in locals():
        f.write(f"Full Dataset Nowcasting - Mean Absolute Error (MAE): {mae_full:.4f}\n")
    if 'mae_5_years_trained' in locals():
        f.write(f"5-Year Trained Nowcasting - Mean Absolute Error (MAE): {mae_5_years_trained:.4f}\n")
print(f"MAE values saved to: {mae_values_path}")