# -*- coding: utf-8 -*-
"""5.Nowcastingmodel.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ci3FQbYFTvitJ5MQZHXWYE79EOHls1D1

## Train Final Nowcasting Model (using Hospitality Index)
"""

from sklearn.ensemble import RandomForestRegressor
import pandas as pd

# 1. Ensure the df DataFrame has the GDP_lag1 and GDP_growth columns
# These columns are typically created earlier in the notebook, but ensure they exist
# for robustness.
if 'GDP_lag1' not in df.columns:
    df['GDP_lag1'] = df['GDP'].shift(1)
if 'GDP_growth' not in df.columns:
    df['GDP_growth'] = df['GDP'].pct_change()

# Filter df for only the last five years
last_available_date = df.index.max()
five_years_ago = last_available_date - pd.DateOffset(years=5)
df_5_years = df[df.index >= five_years_ago]

# 2. Create a new DataFrame, df_final_model, by dropping NaN values from the 5-year subset
df_final_model = df_5_years.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

# 3. Define the feature matrix X_final
X_final = df_final_model[['GDP_lag1', 'hospitality_index']]

# 4. Define the target vector y_final
y_final = df_final_model['GDP_growth']

# 5. Initialize a RandomForestRegressor model
rf_final_nowcast_model = RandomForestRegressor(n_estimators=500, random_state=42)

# 6. Train the model
rf_final_nowcast_model.fit(X_final, y_final)

print("Random Forest Regressor model trained successfully on the last five years of historical data.")
print(f"Number of samples used for training: {len(X_final)}")

"""## Prepare Features for Next Quarter's Nowcast (using Hospitality Index)


"""

import pandas as pd

# 1. Determine the date for which the GDP growth nowcast will be made.
# Get the last date in the DataFrame (which is the end of the last full quarter)
last_available_date = df.index.max()
# The nowcast date will be the next quarter
nowcast_date = last_available_date + pd.DateOffset(months=3)

print(f"Nowcast Date: {nowcast_date.strftime('%Y-%m-%d')}")

# 2. Extract the last known GDP value from the df DataFrame.
# This value will serve as the GDP_lag1 for the nowcast.
gdp_lag1_nowcast = df['GDP'].iloc[-1]
print(f"GDP_lag1 for Nowcast: {gdp_lag1_nowcast}")

# 3. Extract the most recent hospitality_index value from the df DataFrame.
hospitality_index_nowcast = df['hospitality_index'].iloc[-1]
print(f"Hospitality Index for Nowcast: {hospitality_index_nowcast}")

# 4. Create a Pandas DataFrame representing the feature vector for the nowcast.
# It should contain gdp_lag1_nowcast and hospitality_index_nowcast in the same order as X_final.
X_nowcast_features = pd.DataFrame(
    [[gdp_lag1_nowcast, hospitality_index_nowcast]],
    columns=['GDP_lag1', 'hospitality_index'],
    index=[nowcast_date],
)

print("\nFeature vector for next quarter's nowcast (X_nowcast_features):")
print(X_nowcast_features)

"""## Perform Out-of-Sample Nowcast

"""

import pandas as pd

# 1. Use the trained rf_final_nowcast_model to predict the GDP growth
# X_nowcast_features is already a DataFrame with the correct structure
predicted_gdp_growth = rf_final_nowcast_model.predict(X_nowcast_features)[0]

# 2. Store the predicted GDP growth in a variable
# This was already done in the previous step, but explicitly reassign for clarity
predicted_gdp_growth_variable = predicted_gdp_growth

print(f"Predicted GDP Growth for the next quarter: {predicted_gdp_growth_variable:.4f}")

# 3. Calculate the nowcasted GDP value for the next quarter
# gdp_lag1_nowcast contains the GDP from the previous quarter
nowcasted_gdp_value = gdp_lag1_nowcast * (1 + predicted_gdp_growth_variable)

print(f"Nowcasted GDP value for the next quarter: {nowcasted_gdp_value:.2f}")

# Optionally, store the nowcast results in a DataFrame for better tracking
nowcast_output_df = pd.DataFrame({
    'Nowcast Date': [X_nowcast_features.index[0]],
    'GDP_lag1': [gdp_lag1_nowcast],
    'Hospitality Index': [hospitality_index_nowcast],
    'Predicted GDP Growth': [predicted_gdp_growth_variable],
    'Nowcasted GDP Value': [nowcasted_gdp_value],
})
print("\nNowcast Output DataFrame:")
print(nowcast_output_df)

"""## Display Nowcasted GDP


"""

print("Nowcasted GDP for the upcoming quarter:")
print(nowcast_output_df)

print(f"\nSummary: The GDP for the quarter ending {nowcast_output_df['Nowcast Date'].dt.strftime('%Y-%m-%d').iloc[0]} is nowcasted to be {nowcast_output_df['Nowcasted GDP Value'].iloc[0]:.2f} Euro Million, representing a predicted growth of {nowcast_output_df['Predicted GDP Growth'].iloc[0]*100:.2f}% from the previous quarter's GDP of {nowcast_output_df['GDP_lag1'].iloc[0]} Euro Million.")