# -*- coding: utf-8 -*-
"""Run OLS and LASSO Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OMKbWEozfxSOBX9hxNP3I1pCZo9kNkQ

# OLS Regression

###**Run overall OLS regression**
"""

import statsmodels.api as sm

# Define the independent variable (hospitality_index) and add a constant for the full dataset
X_full = sm.add_constant(df[['hospitality_index']])

# Define the dependent variable (GDP) for the full dataset
y_full = df['GDP']

# Run the OLS regression model for the full dataset
model_full = sm.OLS(y_full, X_full).fit()

# Print the summary of the regression results
print(model_full.summary())

"""###**OLS for past five years**"""

import statsmodels.api as sm
import pandas as pd

# Determine the start date for the last five years
five_years_ago = df.index.max() - pd.DateOffset(years=5)

# Filter the DataFrame for the last five years
df_last_5_years = df[df.index >= five_years_ago]

# Define the independent variable (hospitality_index) and add a constant
X_5_years = sm.add_constant(df_last_5_years[['hospitality_index']])

# Define the dependent variable (GDP)
y_5_years = df_last_5_years['GDP']

# Run the OLS regression model for the last five years
model_5_years = sm.OLS(y_5_years, X_5_years).fit()

# Print the summary of the regression results
print(model_5_years.summary())

"""###**Evaluate the regression of the lagges GDP and Hospitality index**"""

importances = rf.feature_importances_
feature_names = X.columns

for name, imp in zip(feature_names, importances):
    print(name, ":", imp)

"""###**Save regression tables and interpretations to files**"""

import os

results_folder = os.path.join(project_root, 'results')
os.makedirs(results_folder, exist_ok=True)

# Prepare the interpretation for the full dataset model
interpretation_full = f"\n\nOLS INTERPRETATION (Full Dataset):\n"
interpretation_full += f"R-squared: {model_full.rsquared:.3f}\n"
interpretation_full += f"Coefficient on hospitality_index: {model_full.params['hospitality_index']:.2f}\n"
if model_full.pvalues['hospitality_index'] < 0.05:
    interpretation_full += "→ Statistically significant.\n"
else:
    interpretation_full += "→ Not statistically significant.\n"

# Save the summary of the full dataset regression model and its interpretation
summary_full_path = os.path.join(results_folder, 'ols_summary_full_dataset.txt')
with open(summary_full_path, 'w') as f:
    f.write(model_full.summary().as_text())
    f.write(interpretation_full)
print(f"Full dataset OLS regression summary and interpretation saved to: {summary_full_path}")

# Prepare the interpretation for the 5-year model
interpretation_5_years = f"\n\nOLS INTERPRETATION (Last 5 Years):\n"
interpretation_5_years += f"R-squared: {model_5_years.rsquared:.3f}\n"
interpretation_5_years += f"Coefficient on hospitality_index: {model_5_years.params['hospitality_index']:.2f}\n"
if model_5_years.pvalues['hospitality_index'] < 0.05:
    interpretation_5_years += "→ Statistically significant.\n"
else:
    interpretation_5_years += "→ Not statistically significant.\n"

# Save the summary of the 5-year regression model and its interpretation
summary_5_years_path = os.path.join(results_folder, 'ols_summary_5_years.txt')
with open(summary_5_years_path, 'w') as f:
    f.write(model_5_years.summary().as_text())
    f.write(interpretation_5_years)
print(f"5-year OLS regression summary and interpretation saved to: {summary_5_years_path}")

"""# LASSO regression

###LASSO regression for full data set
"""

from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import os

# ================q
# 1. Prepare data
# ================q

# Create lagged GDP and GDP growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change
df_model = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

X = df_model[['GDP_lag1', 'hospitality_index']]
y = df_model['GDP_growth']

# Scale predictors (LASSO requires scaling)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ===================
# 2. Run LASSO with CV
# ===================
lasso = LassoCV(cv=5, random_state=42)
lasso.fit(X_scaled, y)

# =========================
# 3. Print model information
# =========================
print("Best alpha (λ):", lasso.alpha_)
print("\nCoefficients:")

coef_table = pd.DataFrame({
    'feature': X.columns,
    'coefficient': lasso.coef_
})

print(coef_table)

# Identify which features LASSO kept
selected_features = coef_table[coef_table['coefficient'] != 0]['feature'].tolist()
zeroed_features = coef_table[coef_table['coefficient'] == 0]['feature'].tolist()

print("\nSelected features (non-zero):", selected_features)
print("Zeroed-out features:", zeroed_features)

# ======================
# 4. Save results
# ======================
results_folder = os.path.join(project_root, 'results')
os.makedirs(results_folder, exist_ok=True)

coef_table.to_csv(os.path.join(results_folder, "lasso_coefficients.csv"))
print("\nSaved coefficient table to /results folder.")

"""### Lasso Regression - Trained on Last 5 Years of Data"""

from sklearn.linear_model import LassoCV
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import os

# Ensure df has the latest lagged and growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change for the full dataset
df_model_full = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

# Filter df_model for only the last five years
five_years_ago_lasso = df_model_full.index.max() - pd.DateOffset(years=5)
df_model_5_years_lasso = df_model_full[df_model_full.index >= five_years_ago_lasso]

# ================q
# 1. Prepare data
# ================q
X_lasso_5_years = df_model_5_years_lasso[['GDP_lag1', 'hospitality_index']]
y_lasso_5_years = df_model_5_years_lasso['GDP_growth']

# Scale predictors (LASSO requires scaling)
scaler_lasso_5_years = StandardScaler()
X_scaled_lasso_5_years = scaler_lasso_5_years.fit_transform(X_lasso_5_years)

# ===================
# 2. Run LASSO with CV
# ===================
lasso_5_years = LassoCV(cv=5, random_state=42)
lasso_5_years.fit(X_scaled_lasso_5_years, y_lasso_5_years)

# =========================
# 3. Print model information
# =========================
print("Best alpha (λ) for 5-year Lasso:", lasso_5_years.alpha_)
print("\nCoefficients for 5-year Lasso:")

coef_table_5_years = pd.DataFrame({
    'feature': X_lasso_5_years.columns,
    'coefficient': lasso_5_years.coef_
})

print(coef_table_5_years)

# Identify which features LASSO kept
selected_features_lasso_5_years = coef_table_5_years[coef_table_5_years['coefficient'] != 0]['feature'].tolist()
zeroed_features_lasso_5_years = coef_table_5_years[coef_table_5_years['coefficient'] == 0]['feature'].tolist()

print("\nSelected features (non-zero) for 5-year Lasso:", selected_features_lasso_5_years)
print("Zeroed-out features for 5-year Lasso:", zeroed_features_lasso_5_years)

# ======================
# 4. Save results
# ======================
results_folder = os.path.join(project_root, 'results')
coef_table_5_years.to_csv(os.path.join(results_folder, "lasso_coefficients_5_years.csv"))
print("\nSaved 5-year Lasso coefficient table to /results folder.")