# -*- coding: utf-8 -*-
"""Set up Nowcasting model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qd1GNeVKUP3nzX-pAC8oyc5P2_onZYGY

# Random Forest Regression

### **Random Forest regression for whole data set**
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd # Import pandas for DataFrame creation

# Create lagged GDP and GDP growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change
df_model = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

X = df_model[['GDP_lag1', 'hospitality_index']]
y = df_model['GDP_growth']

tscv = TimeSeriesSplit(n_splits=5)

all_preds = []
all_actuals = []
all_dates = [] # To store dates for each prediction

for train_idx, test_idx in tscv.split(X):
    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    rf = RandomForestRegressor(n_estimators=500, random_state=42)
    rf.fit(X_train, y_train)

    pred = rf.predict(X_test)
    all_preds.extend(pred)
    all_actuals.extend(y_test.tolist()) # Convert Series to list
    all_dates.extend(y_test.index.tolist()) # Store dates

# Create a DataFrame for easier plotting and filtering
nowcast_results_df = pd.DataFrame({
    'date': all_dates,
    'actual': all_actuals,
    'predicted': all_preds
}).set_index('date').sort_index()

rmse = np.sqrt(mean_squared_error(all_actuals, all_preds))
print("RF RMSE:", rmse)

"""###**Create graph for Full time period of nowcasting**"""

import matplotlib.pyplot as plt
import pandas as pd

plt.figure(figsize=(12, 6))
plt.plot(nowcast_results_df.index, nowcast_results_df['actual'], label="Actual GDP Growth")
plt.plot(nowcast_results_df.index, nowcast_results_df['predicted'], label="Predicted GDP Growth")
plt.legend()
plt.title("Nowcast vs Actual GDP Growth (Full Dataset)")
plt.xlabel("Date")
plt.ylabel("GDP Growth")
plt.grid(True)
plt.show()

"""###**Now cast for the past five years**"""

import matplotlib.pyplot as plt
import pandas as pd

# Determine the start date for the last five years
# Assuming the latest date in your data is nowcast_results_df.index.max()
five_years_ago = nowcast_results_df.index.max() - pd.DateOffset(years=5)

# Filter the DataFrame for the last five years
filtered_results = nowcast_results_df[nowcast_results_df.index >= five_years_ago]

plt.figure(figsize=(12, 6))
plt.plot(filtered_results.index, filtered_results['actual'], label="Actual GDP Growth")
plt.plot(filtered_results.index, filtered_results['predicted'], label="Predicted GDP Growth")
plt.legend()
plt.title("Nowcast vs Actual GDP Growth (Last 5 Years)")
plt.xlabel("Date")
plt.ylabel("GDP Growth")
plt.grid(True)
plt.show()

"""### **Random Forest Regression - Trained on Last 5 Years of Data**"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd

# Ensure df has the latest lagged and growth features
df['GDP_lag1'] = df['GDP'].shift(1)
df['GDP_growth'] = df['GDP'].pct_change()

# Drop rows with NaN values that result from lagging/pct_change for the full dataset
df_model_full = df.dropna(subset=['GDP_lag1', 'GDP_growth', 'hospitality_index'])

# Filter df_model for only the last five years for training
five_years_ago_train = df_model_full.index.max() - pd.DateOffset(years=5)
df_model_5_years_train = df_model_full[df_model_full.index >= five_years_ago_train]

X_5_years_train = df_model_5_years_train[['GDP_lag1', 'hospitality_index']]
y_5_years_train = df_model_5_years_train['GDP_growth']

tscv_5_years = TimeSeriesSplit(n_splits=3) # Reduced splits for potentially smaller dataset

all_preds_5_years = []
all_actuals_5_years = []
all_dates_5_years = []

for train_idx, test_idx in tscv_5_years.split(X_5_years_train):
    X_train_5_years, X_test_5_years = X_5_years_train.iloc[train_idx], X_5_years_train.iloc[test_idx]
    y_train_5_years, y_test_5_years = y_5_years_train.iloc[train_idx], y_5_years_train.iloc[test_idx]

    rf_5_years = RandomForestRegressor(n_estimators=500, random_state=42)
    rf_5_years.fit(X_train_5_years, y_train_5_years)

    pred_5_years = rf_5_years.predict(X_test_5_years)
    all_preds_5_years.extend(pred_5_years)
    all_actuals_5_years.extend(y_test_5_years.tolist())
    all_dates_5_years.extend(y_test_5_years.index.tolist())

# Create a DataFrame for results specific to this 5-year training
nowcast_results_df_5_years_trained = pd.DataFrame({
    'date': all_dates_5_years,
    'actual': all_actuals_5_years,
    'predicted': all_preds_5_years
}).set_index('date').sort_index()

rmse_5_years_trained = np.sqrt(mean_squared_error(all_actuals_5_years, all_preds_5_years))
print("RF RMSE (Model Trained Only on Last 5 Years Data):", rmse_5_years_trained)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(nowcast_results_df_5_years_trained.index, nowcast_results_df_5_years_trained['actual'], label="Actual GDP Growth")
plt.plot(nowcast_results_df_5_years_trained.index, nowcast_results_df_5_years_trained['predicted'], label="Predicted GDP Growth")
plt.legend()
plt.title("Nowcast vs Actual GDP Growth (Model Trained on Last 5 Years)")
plt.xlabel("Date")
plt.ylabel("GDP Growth")
plt.grid(True)
plt.show()

df['hospitality_lag1'] = df['hospitality_index'].shift(1)
df['hospitality_lag2'] = df['hospitality_index'].shift(2)

df['trend_momentum'] = df['hospitality_index'].diff()

df['GDP_growth_lag1'] = df['GDP_growth'].shift(1)

"""###**Save Nowcasting results**"""

import os

results_folder = os.path.join(project_root, 'results')
os.makedirs(results_folder, exist_ok=True)

# Save the full dataset nowcasting results
nowcast_full_path = os.path.join(results_folder, 'nowcast_results_full_dataset.csv')
nowcast_results_df.to_csv(nowcast_full_path)
print(f"Full dataset nowcasting results saved to: {nowcast_full_path}")

# Save the nowcasting results from the model trained on the last five years
nowcast_5yr_trained_path = os.path.join(results_folder, 'nowcast_results_5_years_trained.csv')
nowcast_results_df_5_years_trained.to_csv(nowcast_5yr_trained_path)
print(f"Nowcasting results (model trained on last 5 years) saved to: {nowcast_5yr_trained_path}")